--- 
- name: our first playbook
  hosts: amazon
  become: true
  become_method: sudo 
  tasks:
  - name: Install package 
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items:
    - telnet
    - wget
    - elinks
    - lftp 
    - curl

  - name: Remove package 
    ansible.builtin.package:
      name: "{{ item }}"
      state: absent  
    with_items:
    - lftp 

  - name: Add the users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    with_items:
    - ben
    - lisa
    - kate 
    - dan
    - sam

  - name: Removing users
    ansible.builtin.user:
      name: "{{ item }}"
      state: absent 
    with_items:
    - tim

  - name: Adding a group
    ansible.builtin.group:
      name: "{{ item }}"
      state: present  
    with_items:
    - devops
    - billing 
    - sales
    - marketing
    - dev
    ignore_errors: true

  - name: Deleting groups
    ansible.builtin.group:
      name: "{{ item }}"
      state: absent
    with_items:
    - home
    
...